eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: idOrder
            url: lb://order-service
            predicates:
              - Path=/order
          - id: idUser
            url: lb://user-service
            predicates:
              - Path=/user
          - id: idProduct
            url: lb://product-service
            predicates:
              - Path=/product
          - id: idPayment
            url: lb://payment-service
            predicates:
              - Path=/payment
          - id: idFavourite
            url: lb://favourite-service
            predicates:
              - Path=/favourite

server:
  port: 9093
