server:
  port: 9192

spring:
  web:
    resource:
      static-location: classpath:/static/
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3333/ecommercestore
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQLDialect

redis:
  host: localhost
  port: 6378

token:
  key: fSZcTeAPU7nPu0SmOcKaQMpc4G+5Pb6hRrDDVRnT5IA=

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka
  instance:
    prefer-ip-address: true